version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.9
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-23-21-227-73.compute-1.amazonaws.com
            port: '5432'
            database: ddgjdop3jo6ves
            user: iilmxstxxtdpzk
            password: 9a1cf14fcea283364121fe5c1cba3d61070d8eb4411041995299cd6017bca738
            migrations: false